[package]
name = "mu-exec"
version = "0.0.1"
edition = "2021"

[dependencies]
getopt = "1.1.3"
elf = "0.7.4"
mu = { path = "../.." }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.6.0"
