[package]
name = "mux"
version = "0.0.12"
edition = "2021"

[dependencies]
capitalize = "0.3.4"
getopts = "0.2.21"
git2 = "0.19.0"
lazy_static = "1.4.0"
public-api = "0.35.1"
rust-fsm = "0.7.0"
rustdoc-json = "0.9.1"
temp-file = "0.1.8"
upon = "0.8.1"
