[package]
name = "mu-ld"
version = "0.0.1"
edition = "2021"

[dependencies]
getopt = "1.1.3"
object = {version = "0.35.0", features = [ "build_core" ]}
json = "0.12.4"
mu = { path = "../.." }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5.4"
