[package]
name = "sysgen"
version = "0.0.1"
edition = "2021"

[dependencies]
capitalize = "0.3.4"
git2 = "0.19.0"
getopts = "0.2.21"
json = "0.12.4"
lazy_static = "1.4.0"
public-api = "0.35.1"
rustdoc-json = "0.9.1"
upon = "0.8.1"
