[package]
name = "mu-listener"
version = "0.0.3"
edition = "2021"

[dependencies]
json = "0.12"
mu = { path = "../.." }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.6"